
package casa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FacturacionComprobanteWs", targetNamespace = "http://webService/", wsdlLocation = "http://127.0.0.1:8080/FacturacionComprobanteWs/FacturacionComprobanteWs?wsdl")
public class FacturacionComprobanteWs_Service
    extends Service
{

    private final static URL FACTURACIONCOMPROBANTEWS_WSDL_LOCATION;
    private final static WebServiceException FACTURACIONCOMPROBANTEWS_EXCEPTION;
    private final static QName FACTURACIONCOMPROBANTEWS_QNAME = new QName("http://webService/", "FacturacionComprobanteWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/FacturacionComprobanteWs/FacturacionComprobanteWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FACTURACIONCOMPROBANTEWS_WSDL_LOCATION = url;
        FACTURACIONCOMPROBANTEWS_EXCEPTION = e;
    }

    public FacturacionComprobanteWs_Service() {
        super(__getWsdlLocation(), FACTURACIONCOMPROBANTEWS_QNAME);
    }

    public FacturacionComprobanteWs_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FACTURACIONCOMPROBANTEWS_QNAME, features);
    }

    public FacturacionComprobanteWs_Service(URL wsdlLocation) {
        super(wsdlLocation, FACTURACIONCOMPROBANTEWS_QNAME);
    }

    public FacturacionComprobanteWs_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FACTURACIONCOMPROBANTEWS_QNAME, features);
    }

    public FacturacionComprobanteWs_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FacturacionComprobanteWs_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FacturacionComprobanteWs
     */
    @WebEndpoint(name = "FacturacionComprobanteWsPort")
    public FacturacionComprobanteWs getFacturacionComprobanteWsPort() {
        return super.getPort(new QName("http://webService/", "FacturacionComprobanteWsPort"), FacturacionComprobanteWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FacturacionComprobanteWs
     */
    @WebEndpoint(name = "FacturacionComprobanteWsPort")
    public FacturacionComprobanteWs getFacturacionComprobanteWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "FacturacionComprobanteWsPort"), FacturacionComprobanteWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FACTURACIONCOMPROBANTEWS_EXCEPTION!= null) {
            throw FACTURACIONCOMPROBANTEWS_EXCEPTION;
        }
        return FACTURACIONCOMPROBANTEWS_WSDL_LOCATION;
    }

}
